/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MemberObjectPageObjectPage journey");

        opaTest("Navigate to MemberObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheProjectList.onFilterBar().iExecuteSearch();

            Then.onTheProjectList.onTable().iCheckRows();
            When.onTheProjectList.onTable().iPressRow(0);

            Then.onTheProjectObjectPage.iSeeThisPage();
            Then.onTheProjectObjectPage.onTable({ property: "team" }).iCheckRows();
            When.onTheProjectObjectPage.onTable({ property: "team" }).iPressRow(0);

            Then.onTheMemberObjectPage.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheMemberObjectPage.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::Detail" });
            Then.onTheMemberObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::Detail",
                field: "role_ID",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMemberObjectPage.iCheckSection({ section: "ProjectsDetails" });
            Then.onTheMemberObjectPage.onForm({ section: "ProjectsDetails" }).iCheckField({ property: "member/email" });
            Then.onTheMemberObjectPage.onForm({ section: "ProjectsDetails" }).iCheckField({ property: "member/division" });
            Then.onTheMemberObjectPage.onForm({ section: "ProjectsDetails" }).iCheckField({ property: "member/department" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});