/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ProjectListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheProjectList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheProjectList.onFilterBar().iCheckFilterField("Project Title");
            Then.onTheProjectList.onFilterBar().iCheckFilterField("Start");
            Then.onTheProjectList.onFilterBar().iCheckFilterField("End");
            Then.onTheProjectList.onFilterBar().iCheckFilterField("Status");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheProjectList.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheProjectList.onFilterBar().iExecuteSearch();
        //     Then.onTheProjectList.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheProjectList.onTable().iCheckColumns(undefined, {"name":{"header":"Project Title"},"description":{"header":"Description"},"startDate":{"header":"Start"},"endDate":{"header":"End"},"status/name":{"header":"Status"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheProjectList.onFilterBar().iExecuteSearch();
            
            Then.onTheProjectList.onTable().iCheckRows();

            When.onTheProjectList.onTable().iPressRow(0);
            Then.onTheProjectObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});